server:
  port: 8080

spring:
  application:
    name: gateway

  cors:
    url:
      - localhost:3000,
      - http://localhost:3000,
      - https://localhost:3000

  cloud:
    discovery:
      client:
        simple:
          instances:
            api-ana:
              - uri: http://localhost:8084

    compatibility-verifier:
      enabled: false
    gateway:
      routes:
        - id: login-service
          uri: http://localhost:8081
          predicates:
            - Path=/login/**, /usuarios/**, /autenticacao/**

        - id: cliente
          uri: http://localhost:8082
          predicates:
            - Path=/clientes/**

        - id: produto
          uri: http://localhost:8083
          predicates:
            - Path=/produtos/**

          filters:
            - name: Retry
              args:
                  retries: 3
                  statuses: BAD_GATEWAY, SERVICE_UNAVAILABLE, NOT_FOUND
                  methods: GET, POST
                  backoff:
                    firstBackoff: 10ms
                    maxBackoff: 50ms
                    factor: 2
                    basedOnPreviousValue: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG